apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mp-api-gateway.fullname" . }}
  labels:
    {{ include "mp-api-gateway.labels" . | nindent 4 }}
data:
  MP_API_GATEWAY_PORT: {{ required "A valid .Values.global.mpApiGatewayPort entry required!" .Values.global.mpApiGatewayPort | quote }}
  MP_KAFKA_REST_PROXY_URL: {{ include "mpKafkaRestProxyUrl" . }}
