apiVersion: v1
kind: Service
metadata:
  name: {{ include "mp-api-gateway.fullname" . }}
  labels:
    {{- include "mp-api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "A valid .Values.global.mpApiGatewayPort entry required!" .Values.global.mpApiGatewayPort }}
      targetPort: {{ required "A valid .Values.global.mpApiGatewayPort entry required!" .Values.global.mpApiGatewayPort }}
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.global.mpApiGatewayNodePort))) }}
      nodePort: {{ .Values.global.mpApiGatewayNodePort }}
{{ end }}
      protocol: TCP
      name: {{ required "A valid .Values.global.mpApiGatewayPortName entry required!" .Values.global.mpApiGatewayPortName }}
  selector:
    {{- include "mp-api-gateway.selectorLabels" . | nindent 4 }}
