server:
  port: ${MP.API.GATEWAY.PORT}

services:
  kafkaRestProxy:
    url: ${MP.KAFKA.REST.PROXY.URL}
  bcClient:
    url: ${MP.BC.CLIENT.URL}
  entityManager:
    url: ${MP.ENTITY.MANAGER.URL}
  signatureVerifier:
    url: ${MP.SIGNATURE.VERIFIER.URL}