replicaCount: 1

image:
  repository: 543164192837.dkr.ecr.eu-central-1.amazonaws.com/mp-api-gateway
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################

recreationFlag: 1

global:
  namespaceName: ""
  recreationFlag: 1
  mpApiGatewayPort: 8050
  mpApiGatewayNodePort: 30444
  mpApiGatewayPortName: http-8050
  mpKafkaRestProxyPort: 8060
  mpBCClientPort: 8070
  mpEntityManagerPort: 8090
  mpSignatureVerifierPort: 8030

service:
  type: ClusterIP

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetAverageCPUUtilization: 70
  targetAverageMemoryUtilization: 70

resources: {}
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 1000m
#    memory: 1024Mi

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################

nodeSelector: {}

tolerations: []

affinity: {}
